[package]
name = "wasabi-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1.4.1"
libfuzzer-sys = "0.4"
wasabi = { path = "../wasabi" }
wasabi_wasm = { path = "../wasabi_wasm" }
wasm-smith = { version = "0.225.0", features = ["wasmparser"] }
wasmparser = "0.225.0"


[[bin]]
name = "wasabi_fuzz"
path = "fuzz_targets/wasabi_fuzz.rs"
test = false
doc = false
bench = false
