[package]
name = "wasabi"
version = "0.2.0"
authors = ["Daniel Lehmann <mail@dlehmann.eu>"]
edition = "2018"

[dev-dependencies]
test_utilities = { path = "lib/test_utilities" }

[dependencies]
wasm = { path = "lib/wasm" }

# for parallel instrumentation of functions
rayon = "1.0"

# for upgradable RW lock during instrumentation
parking_lot = "0.6.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "0.3.0"

[profile.release]
lto = true
# debug = true
