[package]
name = "wasm-instrumentation"
version = "0.1.0"
authors = ["Daniel Lehmann <daniel.lehmann@crisp-da.de>"]

[dependencies]
wasm-derive = { path = "wasm-derive" }
byteorder = "1.2.1"
leb128 = "0.2.2"
rayon = "0.9.0"