[package]
name = "wasm-instrumentation"
version = "0.1.0"
authors = ["Daniel Lehmann <daniel.lehmann@crisp-da.de>"]

[dependencies]
parse-wasm-derive = { path = "parse-wasm-derive" }
byteorder = "1.2.1"
leb128 = "0.2.2"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"