name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  wasabi_wasm:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install wabt && wasm-validate --version
      name: Install WABT
    - run: cargo --version; rustc --version; cargo clippy --version
      name: Rust version
    - run: cargo build
      working-directory: crates/wasabi_wasm/
    - run: cargo clippy
      working-directory: crates/wasabi_wasm/
    - run: cargo test -- --nocapture
      working-directory: crates/wasabi_wasm/
  wasabi:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install wabt && wasm-validate --version
      name: Install WABT
    - run: cargo --version; rustc --version; cargo clippy --version
      name: Rust version
    - run: cargo build
      working-directory: crates/wasabi/
    - run: cargo clippy
      working-directory: crates/wasabi/
    - run: cargo test -- --nocapture
      working-directory: crates/wasabi/
