name: Rust CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  wasabi_wasm:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Rust version
      run: cargo --version; rustc --version; cargo clippy --version
    - run: cd crates/wasabi_wasm/
    - run: cargo build
    - run: cargo clippy
    - run: cargo test -- --nocapture
